# Generated by Django 2.2.6 on 2019-10-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191025_1912'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bill',
        ),
        migrations.AddField(
            model_name='transaction',
            name='participants',
            field=models.ManyToManyField(to='account.User'),
        ),
    ]
