# Generated by Django 2.2.6 on 2019-10-25 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191025_1912'),
        ('ledger', '0002_auto_20191025_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='participants',
        ),
        migrations.AddField(
            model_name='transaction',
            name='participants',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
    ]
